server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/picoideal?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Ydr123ydr
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    connect-timeout: 10s

  jackson:
    time-zone: GMT+8

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: xyz.hsinyuwang.cloud.domain.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  level:
    xyz.hsinyuwang: debug
    org.springframework: warn